"""add behavioral profile fields for policy evaluation

Revision ID: 073738cbc0ec
Revises: 694142a4c8b6
Create Date: 2026-08-01 18:38:34.577945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073738cbc0ec'
down_revision: Union[str, Sequence[str], None] = '694142a4c8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_behaviors', sa.Column('usual_channel', sa.Enum('WEB', 'MOBILE', name='channel', native_enum=False), nullable=False))
    op.add_column('customer_behaviors', sa.Column('account_creation_date', sa.Date(), nullable=False))
    op.add_column('customer_behaviors', sa.Column('last_profile_update', sa.DateTime(timezone=True), nullable=False))
    op.add_column('customer_behaviors', sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('customer_behaviors', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('customer_behaviors', sa.Column('timezone', sa.String(length=64), nullable=False))
    op.add_column('customer_behaviors', sa.Column('segment', sa.Enum('RETAIL', 'PREMIUM', 'BUSINESS', name='segment', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_behaviors', 'segment')
    op.drop_column('customer_behaviors', 'timezone')
    op.drop_column('customer_behaviors', 'currency')
    op.drop_column('customer_behaviors', 'daily_limit')
    op.drop_column('customer_behaviors', 'last_profile_update')
    op.drop_column('customer_behaviors', 'account_creation_date')
    op.drop_column('customer_behaviors', 'usual_channel')
    # ### end Alembic commands ###
