"""add agent errors table

Revision ID: 694142a4c8b6
Revises: 307787653e5e
Create Date: 2026-07-30 01:53:46.666095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694142a4c8b6'
down_revision: Union[str, Sequence[str], None] = '307787653e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['decisions.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_errors_agent'), 'agent_errors', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_errors_case_id'), 'agent_errors', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_errors_case_id'), table_name='agent_errors')
    op.drop_index(op.f('ix_agent_errors_agent'), table_name='agent_errors')
    op.drop_table('agent_errors')
    # ### end Alembic commands ###
