"""add composite indexes for transaction history queries

Revision ID: 699755dfc00e
Revises: 073738cbc0ec
Create Date: 2026-08-01 20:39:03.462263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699755dfc00e'
down_revision: Union[str, Sequence[str], None] = '073738cbc0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.create_index('ix_transactions_customer_ts', 'transactions', ['customer_id', 'timestamp'], unique=False)
    op.create_index('ix_transactions_device_ts', 'transactions', ['device_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_device_ts', table_name='transactions')
    op.drop_index('ix_transactions_customer_ts', table_name='transactions')
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    # ### end Alembic commands ###
