"""add web_search_allowlist and policy_chunks tables

Revision ID: ee4df0d141e9
Revises: 1276e208c3d9
Create Date: 2026-08-03 19:48:17.872436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee4df0d141e9'
down_revision: Union[str, Sequence[str], None] = '1276e208c3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_chunks',
    sa.Column('chunk_id', sa.String(length=16), nullable=False),
    sa.Column('policy_id', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_policy_chunks_policy_id'), 'policy_chunks', ['policy_id'], unique=False)
    # Índice HNSW sobre el embedding: habilita la búsqueda por similitud del
    # RAG de políticas (D8). `vector_cosine_ops` acota el operador a la
    # distancia coseno, que es la que usa la recuperación semántica.
    op.execute(
        "CREATE INDEX ix_policy_chunks_embedding ON policy_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table('web_search_allowlist',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_search_allowlist')
    op.execute("DROP INDEX IF EXISTS ix_policy_chunks_embedding")
    op.drop_index(op.f('ix_policy_chunks_policy_id'), table_name='policy_chunks')
    op.drop_table('policy_chunks')
    # ### end Alembic commands ###
