"""seal arbiter and debate prompt versions

Revision ID: 0eb0292575ab
Revises: f193c092654b
Create Date: 2026-10-06 02:30:31.337917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb0292575ab'
down_revision: Union[str, Sequence[str], None] = 'f193c092654b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('arbiter_prompt_version', sa.String(length=64), nullable=True))
    op.add_column('decisions', sa.Column('debate_pro_fraud_prompt_version', sa.String(length=64), nullable=True))
    op.add_column('decisions', sa.Column('debate_pro_customer_prompt_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'debate_pro_customer_prompt_version')
    op.drop_column('decisions', 'debate_pro_fraud_prompt_version')
    op.drop_column('decisions', 'arbiter_prompt_version')
    # ### end Alembic commands ###
