"""add scoring fields to decisions

Revision ID: 307787653e5e
Revises: ac3bc6c8573d
Create Date: 2026-07-30 01:29:19.598817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307787653e5e'
down_revision: Union[str, Sequence[str], None] = 'ac3bc6c8573d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('decisions', sa.Column('base_confidence', sa.Float(), nullable=True))
    op.add_column('decisions', sa.Column('confidence_rationale', sa.Text(), nullable=True))
    op.add_column('decisions', sa.Column('scoring_version', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'scoring_version')
    op.drop_column('decisions', 'confidence_rationale')
    op.drop_column('decisions', 'base_confidence')
    op.drop_column('decisions', 'risk_score')
    # ### end Alembic commands ###
