"""add web search allowlist and issuer bank

Revision ID: 5730aa53f76d
Revises: 3367ac570a62
Create Date: 2026-08-06 04:15:25.112944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5730aa53f76d'
down_revision: Union[str, Sequence[str], None] = '3367ac570a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_search_allowlist',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.add_column('transactions', sa.Column('issuer_bank', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'issuer_bank')
    op.drop_table('web_search_allowlist')
    # ### end Alembic commands ###
