"""add matched_policies and policy_catalog_version

Revision ID: 8990ef73796f
Revises: 1276e208c3d9
Create Date: 2026-08-04 12:10:38.205759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8990ef73796f'
down_revision: Union[str, Sequence[str], None] = '1276e208c3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('matched_policies', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('decisions', sa.Column('policy_catalog_version', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'policy_catalog_version')
    op.drop_column('decisions', 'matched_policies')
    # ### end Alembic commands ###
