"""seal the explanation prompt version

Revision ID: 8db41fe7465f
Revises: ec429a4e2aa1
Create Date: 2026-08-05 12:43:40.418138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db41fe7465f'
down_revision: Union[str, Sequence[str], None] = 'ec429a4e2aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('explanation_prompt_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'explanation_prompt_version')
    # ### end Alembic commands ###
