"""create customer_behaviors table

Revision ID: 97de35e4842b
Revises: b2a8d4bf4ee2
Create Date: 2026-07-22 01:58:26.978651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97de35e4842b'
down_revision: Union[str, Sequence[str], None] = 'b2a8d4bf4ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_behaviors',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('usual_amount_avg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('usual_hour_start', sa.SmallInteger(), nullable=False),
    sa.Column('usual_hour_end', sa.SmallInteger(), nullable=False),
    sa.Column('usual_countries', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('usual_devices', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_behaviors')
    # ### end Alembic commands ###
