"""create cases, decisions, signals and human_resolutions

Revision ID: ac3bc6c8573d
Revises: 97de35e4842b
Create Date: 2026-07-23 17:35:09.528840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac3bc6c8573d'
down_revision: Union[str, Sequence[str], None] = '97de35e4842b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'ANALYZING', 'DECIDED', 'PENDING_HUMAN', 'RESOLVED', 'FAILED', name='casestatus', native_enum=False), nullable=False),
    sa.Column('customer_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_cases_status_created_at', 'cases', ['status', 'created_at'], unique=False)
    op.create_table('decisions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'CHALLENGE', 'BLOCK', 'ESCALATE_TO_HUMAN', name='decisiontype', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('citations_internal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations_external', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('debate_pro_fraud', sa.Text(), nullable=False),
    sa.Column('debate_pro_customer', sa.Text(), nullable=False),
    sa.Column('agent_route', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('explanation_customer', sa.Text(), nullable=False),
    sa.Column('explanation_audit', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('human_resolutions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', name='humanaction', native_enum=False), nullable=False),
    sa.Column('analyst_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['decisions.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_case_id'), 'signals', ['case_id'], unique=False)
    op.create_index(op.f('ix_signals_code'), 'signals', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_code'), table_name='signals')
    op.drop_index(op.f('ix_signals_case_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('human_resolutions')
    op.drop_table('decisions')
    op.drop_index('ix_cases_status_created_at', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
