"""create policy catalog tables

Revision ID: ec429a4e2aa1
Revises: 8990ef73796f
Create Date: 2026-08-05 02:55:24.651636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ec429a4e2aa1'
down_revision: Union[str, Sequence[str], None] = '8990ef73796f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding_sets',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source_catalog', sa.String(), nullable=False),
    sa.Column('fingerprint_algorithm', sa.String(length=16), nullable=False),
    sa.Column('fingerprint_field', sa.String(length=32), nullable=False),
    sa.Column('reference_currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_index('uq_binding_sets_single_active', 'binding_sets', ['active'], unique=True, postgresql_where=sa.text('active'))
    op.create_table('fraud_policies',
    sa.Column('policy_id', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('policy_id', 'version')
    )
    op.create_table('policy_bindings',
    sa.Column('binding_set_version', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=16), nullable=False),
    sa.Column('source_version', sa.String(length=32), nullable=False),
    sa.Column('source_fingerprint', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'CHALLENGE', 'BLOCK', 'ESCALATE_TO_HUMAN', name='decisiontype', native_enum=False), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_reason', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('bound_by', sa.String(), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['binding_set_version'], ['binding_sets.version'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id', 'source_version'], ['fraud_policies.policy_id', 'fraud_policies.version'], ),
    sa.PrimaryKeyConstraint('binding_set_version', 'policy_id')
    )
    op.create_table('policy_chunks',
    sa.Column('index_version', sa.String(length=64), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=16), nullable=False),
    sa.Column('source_version', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id', 'source_version'], ['fraud_policies.policy_id', 'fraud_policies.version'], ),
    sa.PrimaryKeyConstraint('index_version', 'chunk_id')
    )
    op.add_column('decisions', sa.Column('retrieval_index_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'retrieval_index_version')
    op.drop_table('policy_chunks')
    op.drop_table('policy_bindings')
    op.drop_table('fraud_policies')
    op.drop_index('uq_binding_sets_single_active', table_name='binding_sets', postgresql_where=sa.text('active'))
    op.drop_table('binding_sets')
    # ### end Alembic commands ###
