"""seal which intelligence snapshot informed the decision

Revision ID: f193c092654b
Revises: 5730aa53f76d
Create Date: 2026-08-06 05:24:18.794514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f193c092654b'
down_revision: Union[str, Sequence[str], None] = '5730aa53f76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('threat_intel_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'threat_intel_version')
    # ### end Alembic commands ###
