/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Casos
         * @description La cola HITL (§3 del contrato): `GET /cases?status=PENDING_HUMAN` es
         *     la vista que el dashboard filtra. El índice `ix_cases_status_created_at`
         *     ya está pensado para este `WHERE status = ... ORDER BY created_at`.
         */
        get: operations["listar_casos_api_v1_cases_get"];
        put?: never;
        /**
         * Crear Caso
         * @description `transaction_id` es la clave de idempotencia (§2.4 del contrato):
         *     existente → `200` con el `case_id` existente, sin volver a correr el
         *     grafo; nuevo → `202`, arranca en segundo plano.
         *
         *     El `IntegrityError` en el `except` no es paranoia: dos requests con el
         *     mismo `transaction_id` casi en simultáneo pueden pasar los dos el
         *     `SELECT` antes de que cualquiera commitee — la unicidad la garantiza la
         *     base (`cases_transaction_id_key`), no este chequeo, que sólo evita la
         *     vuelta al grafo en el caso común.
         */
        post: operations["crear_caso_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle Caso */
        get: operations["detalle_caso_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolver Caso
         * @description W3 (§7.3 del contrato): el grafo ya terminó -`PENDING_HUMAN` es
         *     terminal, no hay `interrupt()` que reanudar (ADR de la etapa del grafo)-,
         *     así que resolver es sólo escribir `human_resolutions` y pasar el caso a
         *     `RESOLVED`. Sólo válido sobre un caso que de verdad está esperando: otro
         *     estado es `409`, no una resolución que reescriba lo que W2 ya decidió.
         */
        post: operations["resolver_caso_api_v1_cases__case_id__resolution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progreso Caso
         * @description No es fuente de verdad (§7.3 del contrato) — `GET /cases/{case_id}`
         *     sigue siendo la única forma confiable de conocer el veredicto; esto es
         *     puramente un agregado visual para la demo en vivo del dashboard.
         */
        get: operations["progreso_caso_api_v1_cases__case_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metricas Llm
         * @description Resumen (costo, latencia, tokens, tasa de error) + desglose por nodo
         *     real del grafo. Cacheado en proceso (`CACHE_TTL_SEGUNDOS`) para no
         *     golpear la API de LangSmith en cada poll del dashboard si hay varias
         *     pestañas abiertas.
         *
         *     `force=true` (ADR-0020) salta el caché para esa llamada puntual —lo usa
         *     el dashboard cuando el stream SSE de un caso avisa que terminó, para
         *     reflejar su costo sin esperar hasta 30s— y **actualiza** el caché con
         *     el resultado fresco, así el próximo poll normal de cualquier pestaña
         *     también se beneficia en vez de volver a pedirlo.
         */
        get: operations["metricas_llm_api_v1_metrics_llm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Politicas
         * @description El catálogo ya vive en `app.state` —lo arma el `lifespan`, no este
         *     endpoint—: releerlo por request revalidaría dos archivos por nada.
         */
        get: operations["listar_politicas_api_v1_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Predicados */
        get: operations["listar_predicados_api_v1_predicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: el proceso responde. No toca la base.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: Postgres responde. Un `SELECT 1` sin éxito propaga la
         *     excepción a un `500` — la señal correcta para un probe, no un caso a
         *     degradar.
         *
         *     La sesión llega por `Depends`, no por `AsyncSessionLocal` directo:
         *     es lo que le permite a un test sobreescribirla con un doble sin
         *     tocar Postgres — ver `tests/test_api_health.py`.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Spa
         * @description Sirve el SPA. Un archivo real del root de `dist/` (p.ej.
         *     `favicon.svg`) se sirve por su nombre exacto; cualquier otra ruta
         *     es del router del lado del cliente (React Router) y cae a
         *     `index.html` — `StaticFiles(html=True)` sólo resuelve URLs de
         *     directorio, no rutas profundas como `/cases/{id}`.
         */
        get: operations["dashboard_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CaseCreated
         * @description Respuesta del POST /cases (202 nuevo / 200 reintento idempotente).
         */
        CaseCreated: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            status: components["schemas"]["CaseStatus"];
        };
        /**
         * CaseDetail
         * @description Respuesta del GET /cases/{case_id}.
         */
        CaseDetail: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            customer: components["schemas"]["CustomerBehaviorRead"] | null;
            decision: components["schemas"]["DecisionRead"] | null;
            human_resolution: components["schemas"]["HumanResolutionRead"] | null;
            status: components["schemas"]["CaseStatus"];
            transaction: components["schemas"]["TransactionRead"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "RECEIVED" | "ANALYZING" | "DECIDED" | "PENDING_HUMAN" | "RESOLVED" | "FAILED";
        /**
         * CaseSummary
         * @description Proyección plana para la cola HITL (GET /cases).
         */
        CaseSummary: {
            /** Amount */
            amount: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id: string;
            decision: components["schemas"]["DecisionType"] | null;
            status: components["schemas"]["CaseStatus"];
        };
        /**
         * Channel
         * @enum {string}
         */
        Channel: "web" | "mobile";
        /** CustomerBehaviorRead */
        CustomerBehaviorRead: {
            /**
             * Account Creation Date
             * Format: date
             */
            account_creation_date: string;
            /** Currency */
            currency: string;
            /** Customer Id */
            customer_id: string;
            /** Daily Limit */
            daily_limit: string;
            /**
             * Last Profile Update
             * Format: date-time
             */
            last_profile_update: string;
            segment: components["schemas"]["Segment"];
            /** Timezone */
            timezone: string;
            /** Usual Amount Avg */
            usual_amount_avg: string;
            usual_channel: components["schemas"]["Channel"];
            /** Usual Countries */
            usual_countries: string[];
            /** Usual Devices */
            usual_devices: string[];
            /** Usual Hour End */
            usual_hour_end: number;
            /** Usual Hour Start */
            usual_hour_start: number;
        };
        /** DebateSummary */
        DebateSummary: {
            /** Pro Customer Argument */
            pro_customer_argument: string;
            /** Pro Fraud Argument */
            pro_fraud_argument: string;
        };
        /** DecisionRead */
        DecisionRead: {
            /** Agent Route */
            agent_route: string[];
            /** Base Confidence */
            base_confidence?: number | null;
            /** Citations External */
            citations_external: components["schemas"]["ExternalCitation"][];
            /** Citations Internal */
            citations_internal: components["schemas"]["InternalCitation"][];
            /** Confidence */
            confidence: number;
            /** Confidence Rationale */
            confidence_rationale?: string | null;
            debate: components["schemas"]["DebateSummary"];
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            decision: components["schemas"]["DecisionType"];
            /** Degraded Agents */
            degraded_agents: string[];
            /** Explanation Audit */
            explanation_audit: string;
            /** Explanation Customer */
            explanation_customer: string;
            /** Explanation Prompt Version */
            explanation_prompt_version?: string | null;
            /**
             * Matched Policies
             * @default []
             */
            matched_policies: string[];
            /** Policy Catalog Version */
            policy_catalog_version?: string | null;
            /** Retrieval Index Version */
            retrieval_index_version?: string | null;
            /** Risk Score */
            risk_score?: number | null;
            /** Scoring Version */
            scoring_version?: string | null;
            /** Signals */
            signals: components["schemas"]["SignalRead"][];
            /** Threat Intel Version */
            threat_intel_version?: string | null;
        };
        /**
         * DecisionType
         * @enum {string}
         */
        DecisionType: "APPROVE" | "CHALLENGE" | "BLOCK" | "ESCALATE_TO_HUMAN";
        /** ExternalCitation */
        ExternalCitation: {
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Summary */
            summary: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HumanAction
         * @enum {string}
         */
        HumanAction: "APPROVE" | "REJECT";
        /**
         * HumanResolutionIn
         * @description Body del POST /cases/{case_id}/resolution.
         */
        HumanResolutionIn: {
            action: components["schemas"]["HumanAction"];
            /** Analyst Id */
            analyst_id: string;
            /** Notes */
            notes?: string | null;
        };
        /** HumanResolutionRead */
        HumanResolutionRead: {
            action: components["schemas"]["HumanAction"];
            /** Analyst Id */
            analyst_id: string;
            /** Notes */
            notes?: string | null;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at: string;
        };
        /** InternalCitation */
        InternalCitation: {
            /** Chunk Id */
            chunk_id: string;
            /** Policy Id */
            policy_id: string;
            /** Version */
            version: string;
        };
        /** LlmMetricsRead */
        LlmMetricsRead: {
            /** Available */
            available: boolean;
            /** Nodes */
            nodes?: components["schemas"]["LlmNodeMetrics"][] | null;
            /** Project */
            project?: string | null;
            summary?: components["schemas"]["LlmMetricsSummary"] | null;
        };
        /** LlmMetricsSummary */
        LlmMetricsSummary: {
            /** Avg Cost Per Decision */
            avg_cost_per_decision: number;
            /** Error Rate */
            error_rate: number;
            /** Latency P50 Seconds */
            latency_p50_seconds: number;
            /** Latency P99 Seconds */
            latency_p99_seconds: number;
            /** Run Count */
            run_count: number;
            /** Total Cost */
            total_cost: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** LlmNodeMetrics */
        LlmNodeMetrics: {
            /** Avg Cost */
            avg_cost: number;
            /** Avg Latency Seconds */
            avg_latency_seconds: number;
            /** Avg Tokens */
            avg_tokens: number;
            /** Name */
            name: string;
            /** Run Count */
            run_count: number;
        };
        /** Page[CaseSummary] */
        Page_CaseSummary_: {
            /** Items */
            items: components["schemas"]["CaseSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ParamSpecRead */
        ParamSpecRead: {
            /**
             * Choices
             * @default []
             */
            choices: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "number" | "integer" | "choice";
            /** Label */
            label: string;
            /** Maximum */
            maximum?: number | null;
            /** Minimum */
            minimum?: number | null;
        };
        /**
         * PolicyRead
         * @description Respuesta de `GET /api/v1/policies` (ADR-0017: sólo lectura, sobre el
         *     catálogo de Fase 2 — `domain.catalog.Policy`, no una tabla).
         */
        PolicyRead: {
            action?: components["schemas"]["DecisionType"] | null;
            /** Bound By */
            bound_by?: string | null;
            /** Evaluable */
            evaluable: boolean;
            /** Excluded Reason */
            excluded_reason?: string | null;
            /** Policy Id */
            policy_id: string;
            state: components["schemas"]["PolicyState"];
            /** Text */
            text: string;
            /** Version */
            version: string;
        };
        /**
         * PolicyState
         * @enum {string}
         */
        PolicyState: "active" | "excluded" | "pending" | "stale";
        /**
         * PredicateSpec
         * @description Respuesta de `GET /api/v1/predicates`: la biblioteca para el
         *     compositor del dashboard (§2.3, §3.3 del contrato).
         *
         *     Sin `fn` ni el valor crudo de `signal`: el primero no es serializable, y
         *     el segundo puede depender de los parámetros (`count_in_window` elige
         *     entre `DEVICE_VELOCITY`/`CUSTOMER_VELOCITY` según el eje) — mostrar sólo
         *     el caso estático confundiría más de lo que informa.
         */
        PredicateSpec: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["ParamSpecRead"];
            };
            /** Requires */
            requires: string[];
            severity: components["schemas"]["Severity"];
        };
        /**
         * Segment
         * @description Segmento comercial del cliente.
         *
         *     Es enum y no `varchar` libre porque la aplicación **agrupa por él**: FP-08
         *     compara el monto contra el promedio del segmento. Un texto libre admitiría
         *     `Retail` y `retail` como grupos distintos y partiría el promedio en dos sin
         *     que nada falle.
         * @enum {string}
         */
        Segment: "retail" | "premium" | "business";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high";
        /** SignalRead */
        SignalRead: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            severity: components["schemas"]["Severity"];
        };
        /**
         * TransactionIn
         * @description Entrada canónica de una transacción a evaluar.
         */
        TransactionIn: {
            /** Amount */
            amount: number | string;
            channel: components["schemas"]["Channel"];
            /** Country */
            country: string;
            /** Currency */
            currency: string;
            /** Customer Id */
            customer_id: string;
            /** Device Id */
            device_id: string;
            /** Issuer Bank */
            issuer_bank?: string | null;
            /** Merchant Id */
            merchant_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Transaction Id */
            transaction_id: string;
        };
        /** TransactionRead */
        TransactionRead: {
            /** Amount */
            amount: string;
            channel: components["schemas"]["Channel"];
            /** Country */
            country: string;
            /** Currency */
            currency: string;
            /** Customer Id */
            customer_id: string;
            /** Device Id */
            device_id: string;
            /** Issuer Bank */
            issuer_bank?: string | null;
            /** Merchant Id */
            merchant_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Transaction Id */
            transaction_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_casos_api_v1_cases_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CaseStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CaseSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_caso_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_caso_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolver_caso_api_v1_cases__case_id__resolution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumanResolutionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progreso_caso_api_v1_cases__case_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metricas_llm_api_v1_metrics_llm_get: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmMetricsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_politicas_api_v1_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRead"][];
                };
            };
        };
    };
    listar_predicados_api_v1_predicates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredicateSpec"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    dashboard_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
